#!/bin/bash

## RUN THIS SCRIPT FROM THE ROOT PROJECT DIRECTORY
## UNCOMMENT THE LINE THAT MATCHES YOUR OPERATING SYSTEM

rm -r sqlite

##### LINUX #####
# curl -o sqlite3.zip https://www.sqlite.org/2019/sqlite-tools-linux-x86-3300000.zip

##### MAC-OSX #####
# curl -o sqlite3.zip https://www.sqlite.org/2019/sqlite-tools-osx-x86-3300000.zip

unzip sqlite3.zip -d sqlite
rm sqlite3.zip
